### ISSUE TITLE
Gráfico incorrecto con grabación a 0

### ISSUE THREAD

**Issue by saa1002** [als1005/GESPRO_PracticaGestionTareas_2021#22]

**Comment by als1005** [comment]
Cuando todos los registros de la grabación están a 0 el gráfico no se construye correctamente.
![46fc1660-e497-11e6-8099-496fe0ee310f](https://user-images.githubusercontent.com/74177242/100549198-c7389700-3271-11eb-8abf-ac94e9458167.jpeg)
