### ISSUE TITLE
Actualizar Técnicas y Herramientas

### ISSUE THREAD

**Issue by saa1002** [als1005/GESPRO_PracticaGestionTareas_2021#28]

**Comment by als1005** [comment]
- [x] Gradle / Maven
- [x]  JavaFx
- [x]  Patrones: Repository, ViewHolder, Builder, Singleton
- [x]  Android
- [x]  Realm
- [x]  Jacabo / VNTNumberPickerPreference / Permission Utils
- [x]  Google Play Services
- [x]  MPAndroidChart-
- [x]  reStructuredText / Sphinx
- [x]  Github Pages
- [x]  OpenWeatherMaps
- [x]  https://translate.google.com/toolkit
- [x]  Material Design
