### ISSUE TITLE
Manual del programador 

### ISSUE THREAD

**Issue by saa1002** [als1005/GESPRO_PracticaGestionTareas_2021#40]

**Comment by als1005** [comment]
- [x] Instalación Android Studio
- [x] Importación del proyecto
- [x] Estructura directorios
- [x] Ejecución tests en local
- [x] Servicios de integración continua
- [x] Creación de un ejecutable
- [x] Plataforma de desarrollo del algoritmo
- [x] Plataforma de conteo
